#!/usr/bin/env python3
"""
Convert code/transfer_CRRA_wage.ipynb to a script with shrunken grids and run it, so the
notebook's execution order and its counterfactual cells are actually exercised.

    python3 tools/nb_smoketest.py            # generate + run
    python3 tools/nb_smoketest.py --gen-only # just write the script

run_all.jl covers only the baseline path. This covers everything else: the counterfactuals,
the subjective-expectations build, the theta arms and every plotting cell. It is the only
check that the notebook runs top-to-bottom on a fresh kernel.

Exit code 0 means every code cell executed.
"""
import json, re, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
NB   = ROOT / "code" / "transfer_CRRA_wage.ipynb"
OUT  = ROOT / "code" / "_nb_smoketest.jl"

# grid shrinks: keep the structure, cut the cost
SUBS = [
    (r'\bNa\s*=\s*50', 'Na=12'), (r'\bNk\s*=\s*50', 'Nk=12'), (r'\bNt\s*=\s*10', 'Nt=4'),
    (r'\bNa\s*=\s*30', 'Na=8'),  (r'\bNhc\s*=\s*30', 'Nhc=8'),
    (r'simN\s*=\s*5000', 'simN=200'),
    (r'bin_edges\s*=\s*1\.0:0\.1:3\.0', 'bin_edges = 1.0:1.0:3.0'),
]

def build():
    nb = json.load(open(NB))
    out = ['# AUTO-GENERATED by tools/nb_smoketest.py — do not edit, do not commit.\n',
           'using Printf\nENV["GKSwstype"] = "100"   # headless Plots\n']
    n = 0
    for i, c in enumerate(nb['cells']):
        if c['cell_type'] != 'code':
            continue
        s = ''.join(c['source'])
        for a, b in SUBS:
            s = re.sub(a, b, s)
        # every constructor must carry the reduced simN, or simulate_model_hetero!'s
        # length guards fire on a mismatch between belief_type and model.simN
        s = re.sub(r'(Parent_child_interaction_age_specific_AR1\()(?![^)]*simN)', r'\1simN=200, ', s)
        s = re.sub(r'(ConSavLaborCollege_AR1\()(?![^)]*simN)', r'\1simN=200, ', s)
        out.append(f'\nprintln("\\n>>> CELL {i}"); flush(stdout)\n{s}\n')
        n += 1
    OUT.write_text(''.join(out))
    return n

def main():
    n = build()
    print(f"generated {OUT.relative_to(ROOT)} from {n} code cells")
    if "--gen-only" in sys.argv:
        return 0
    r = subprocess.run(["julia", "--project=..", OUT.name], cwd=ROOT / "code")
    OUT.unlink(missing_ok=True)
    print("\nSMOKE TEST", "PASSED" if r.returncode == 0 else f"FAILED (exit {r.returncode})")
    return r.returncode

if __name__ == "__main__":
    sys.exit(main())
